---
title: "Development actions history"
output: html_document
editor_options:
  chunk_output_type: console
---

All commands that you use to use when developing packages...

# Start using git

```{r, eval=FALSE}
usethis::use_git()
# Deal with classical files to ignore
usethis::git_vaccinate()
# Use main for primary branch
usethis::git_default_branch_rename()
```

# Package development tools
## Use once

```{r, eval=FALSE}
# package-level documentation
usethis::use_package_doc()

# GitHub
# Add your credentials for GitHub
usethis::create_github_token()
gitcreds::gitcreds_set()

# _Or one step at a time
# Send your project to a new GitHub project (included in `init_share_on_github()`)
usethis::use_github()

# Set Continuous Integration
# _GitHub (included in `init_share_on_github()`)
usethis::use_github_action_check_standard()
usethis::use_github_action("pkgdown")
usethis::use_github_action("test-coverage")
# _GitLab
gitlabr::use_gitlab_ci(type = "check-coverage-pkgdown")
```

## Use everytime needed

```{r, eval=FALSE}
# Simulate package installation
pkgload::load_all()

# Generate documentation and deal with dependencies
attachment::att_amend_desc(update.config = TRUE, extra.suggests = "pkgload")

# Check the package
devtools::check()

# Add a new flat template
fusen::add_flat_template("add")
```

# Share the package

```{r, eval=FALSE}
# set and try pkgdown documentation website locally
usethis::use_pkgdown()
pkgdown::build_site()

# build the tar.gz with vignettes to share with others
devtools::build(vignettes = TRUE)

# Share your package and its documentation on GitHub
# usethis::create_github_token()
# gitcreds::gitcreds_set()
fusen::init_share_on_github()
```
