flat_regex_brick.Rmd:
  path: dev/flat_regex_brick.Rmd
  state: active
  R:
  - R/build_a_regex_brick.R
  - R/validate_regex.R
  tests:
  - tests/testthat/test-build_a_regex_brick.R
  - tests/testthat/test-validate_regex.R
  vignettes: []
  inflate:
    flat_file: dev/flat_regex_brick.Rmd
    vignette_name: .na
    open_vignette: false
    check: false
    document: true
    overwrite: ask
flat_word_generator.Rmd:
  path: dev/flat_word_generator.Rmd
  state: active
  R:
  - R/generate_from_brick.R
  - R/generate_from_regex.R
  - R/search_in_scrabble.R
  tests:
  - tests/testthat/test-generate_from_brick.R
  - tests/testthat/test-search_in_scrabble.R
  - tests/testthat/test-generate_from_regex.R
  vignettes: []
  inflate:
    flat_file: dev/flat_word_generator.Rmd
    vignette_name: .na
    open_vignette: false
    check: false
    document: true
    overwrite: ask
keep:
  path: keep
  state: active
  R:
  - R/doc_color_pal.R
  - R/_disable_autoload.R
  - R/doc_wordlist.R
  - R/app_config.R
  - R/app_server.R
  - R/app_ui.R
  - R/fct_helpers.R
  - R/golem_utils_server.R
  - R/golem_utils_ui.R
  - R/lurex-package.R
  - R/mod_combine_brick.R
  - R/mod_invent_brick.R
  - R/mod_regex_brick.R
  - R/run_app.R
  tests:
  - tests/testthat/test-golem_utils_server.R
  - tests/testthat/test-golem_utils_ui.R
  - tests/testthat/test-golem-recommended.R
  - tests/testthat/test-mod_combine_brick.R
  - tests/testthat/test-mod_invent_brick.R
  - tests/testthat/test-mod_regex_brick.R
  vignettes: []
