---
title: "Build bricks"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

## Build a regex brick

```{r function-build_a_regex_brick}
#' Build a regex brick
#'
#' @param type character. The type of regex group.
#' Can be "ordered" or "unordered".
#' @param content character. The content of the regex group.
#' Can be "wildcard", "lowercase letters", "uppercase letters", "digits",
#' "punctuation", "space and tab", or "custom".
#' @param occurrence character. The occurrence of the regex group.
#' Can be "once", "at least once", "anytime", or "custom".
#' @param custom_motif character. The custom motif to be used in a regex group.
#' Only applicable if "custom" is selected for the content parameter.
#' @param custom_occurrence integer. The occurrence to be used in a regex group.
#' Only applicable if "custom" is selected for the occurrence parameter.
#' @param escape logical. Should special characters in custom motif be escaped.
#'
#' @importFrom stringr str_escape
#'
#' @return A character string representing the built regex.
#' @export
#'
#' @examples
build_a_regex_brick <- function(
    type = c("ordered", "unordered"),
    content = c(
      "wildcard",
      "lowercase letters",
      "uppercase letters",
      "digits",
      "punctuation",
      "space and tab",
      "custom"
    ),
    occurrence = c("once", "at least once", "anytime", "custom"),
    custom_motif = NULL,
    custom_occurrence = NULL,
    escape = TRUE) {
  # check input
  type <- match.arg(type)
  content <- match.arg(content, several.ok = TRUE)
  occurrence <- match.arg(occurrence)

  # check cusom
  if ("custom" %in% occurrence && is.null(custom_occurrence)) {
    stop("custom occurrence selected but no value given")
  }
  if ("custom" %in% content && is.null(custom_motif)) {
    stop("custom motif selected but no value given")
  }

  # escape special character
  if (!is.null(custom_motif) && isTRUE(escape)) {
    # escape special
    unescaped_motif <- custom_motif
    custom_motif <- str_escape(custom_motif)
    # avoid creating range in unordered input with `-`
    if (type == "unordered" && grepl("-", custom_motif)) {
      custom_motif <- paste0("-", gsub("-", "", custom_motif))
    }
  }

  # set occurrence
  if (occurrence != "custom") {
    occurrence_equivalence <- list(
      "once" = "",
      "at least once" = "+",
      "anytime" = "*"
    )
    custom_occurrence <- NULL
    freq <- occurrence_equivalence[occurrence]
  } else {
    freq <- sprintf(
      "{%s,%s}",
      custom_occurrence[1],
      sub("no max", "", custom_occurrence[2])
    )
  }

  # set group
  if (type == "ordered") {
    group_bracket <- c("(", ")")

    # we only allow custom motif for ordered group for now
    text <- sprintf(
      "%s%s%s%s",
      group_bracket[1],
      custom_motif,
      group_bracket[2],
      freq
    )
    # remove unused parameters
    content <- NULL
  } else if (type == "unordered") {
    group_bracket <- c("[", "]")

    # set content
    regex_equivalance <- c(
      "wildcard" = ".",
      "lowercase letters" = "[:lower:]",
      "uppercase letters" = "[:upper:]",
      "digits" = "[:digit:]",
      "punctuation" = "[:punct:]",
      "space and tab" = "[:blank:]",
      "custom" = custom_motif
    )

    text <- sprintf(
      "%s%s%s%s",
      group_bracket[1],
      paste(regex_equivalance[content], collapse = ""),
      group_bracket[2],
      freq
    )
  }

  new_brick <- list(
    brick = text,
    type = type,
    content = content,
    occurrence = occurrence,
    custom_motif = unescaped_motif,
    custom_occurrence = custom_occurrence
  )

  return(new_brick)
}
```

```{r examples-build_a_regex_brick}
build_a_regex_brick(
  type = "ordered",
  occurrence = "custom",
  custom_motif = "hello$",
  custom_occurrence = c(1, 5)
)

build_a_regex_brick(
  type = "unordered",
  occurrence = "anytime",
  custom_motif = "hello!",
  content = c("punctuation", "custom")
)
```

```{r tests-build_a_regex_brick}
test_that("function returns error for unexpected input", {
  expect_error({
    build_a_regex_brick(type = "unknown")
  })
  expect_error({
    build_a_regex_brick(content = "unknown")
  })
  expect_error({
    build_a_regex_brick(occurrence = "unknown")
  })
  expect_error(
    {
      build_a_regex_brick(occurrence = "custom")
    },
    regexp = "custom occurrence selected but no value given"
  )
  expect_error(
    {
      build_a_regex_brick(content = "custom")
    },
    regexp = "custom motif selected but no value given"
  )
})

test_that("function gives expected regex for ordered type", {
  regex_output <- build_a_regex_brick(
    type = "ordered",
    occurrence = "custom",
    custom_motif = "hello",
    custom_occurrence = c("1", "no max")
  )
  expect_equal(object = regex_output$brick, expected = "(hello){1,}")
})

test_that("function gives expected regex for unordered type", {
  regex_output <- build_a_regex_brick(
    type = "unordered",
    occurrence = "anytime",
    custom_motif = "hello",
    content = c("lowercase letters", "uppercase letters", "custom")
  )
  expect_equal(
    object = regex_output$brick,
    expected = "[[:lower:][:upper:]hello]*"
  )
})
```

## Validate a regex brick

```{r function-validate_regex}
#' Validate a regex combination
#'
#' @param bricks character. The ordered list of regex bricks
#' @param use_toast logical. Should a UI toast be shown for incorrect regex.
#'
#' @return logical. Side effect : trigger a toast widget
#' @export
#'
#' @examples
validate_regex <- function(
    bricks,
    use_toast = TRUE) {
  # get idx
  or_idx <- which(bricks == "or")
  start_idx <- which(bricks == "start")
  end_idx <- which(bricks == "end")

  if (all(bricks %in% c("start", "end", "stop"))) {
    return(FALSE)
  }

  if ("start" %in% bricks) {
    # start can be found as 1st element or after a "or"
    if (!all(start_idx %in% c(1, or_idx + 1))) {
      make_a_toast(
        text = "start `^` should be the first element",
        use_toast = use_toast
      )
      return(FALSE)
    }
  }

  if ("end" %in% bricks) {
    if (!all(end_idx %in% c(length(bricks), or_idx - 1))) {
      make_a_toast(
        text = "end `$` should be the last element",
        use_toast = use_toast
      )
      return(FALSE)
    }
  }

  if ("or" %in% bricks) {
    is_first_or_last <- any(c(1, length(bricks)) %in% or_idx)

    if (is_first_or_last) {
      # cannot be first or last
      make_a_toast(
        text = "or `|` should not be 1st or last element",
        use_toast = use_toast
      )
      return(FALSE)
    }

    right_idx <- or_idx + 1[or_idx != length(bricks)]
    left_idx <- or_idx - 1[or_idx != 1]

    is_next_to_or <- any(
      c("or") %in% bricks[c(left_idx, right_idx)]
    )
    is_right_to_start <- any(
      "start" %in% bricks[left_idx]
    )
    is_left_to_end <- any(
      "end" %in% bricks[right_idx]
    )

    if (is_next_to_or) {
      make_a_toast(
        text = "or `|` should not be next to another `|`",
        use_toast = use_toast
      )
      return(FALSE)
    }

    if (is_right_to_start) {
      make_a_toast(
        text = "or `|` should not be directly after start `^`",
        use_toast = use_toast
      )
      return(FALSE)
    }

    if (is_left_to_end) {
      make_a_toast(
        text = "or `|` should not be directly before end `$`",
        use_toast = use_toast
      )
      return(FALSE)
    }
  }
  return(TRUE)
}

#' make a toast
#'
#' @param text character. The text to sho
#' @inheritParams validate_regex use_toast
#'
#' @importFrom shinyWidgets show_toast
#'
#' @noRd
make_a_toast <- function(text, use_toast) {
  if (isTRUE(use_toast)) {
    show_toast(
      title = "woups",
      text = text,
      type = "warning",
      timer = 3000,
      width = "400px",
      position = "top-end"
    )
  }
}
```

```{r examples-validate_regex}
validate_regex(
  bricks = list("1", "end", "or", "2", "end", "or", "3", "4", "end")
)
```

```{r tests-validate_regex}
test_that("function returns TRUE for correct regex", {
  expect_true({
    validate_regex(bricks = list("yes", "or", "no"))
  })
  expect_true({
    validate_regex(
      bricks = list("1", "end", "or", "2", "end", "or", "3", "4", "end")
    )
  })
})

test_that("function returns FALSE for incorrect regex", {
  expect_false({
    validate_regex(
      bricks = list("or", "yes", "no"),
      use_toast = FALSE
    )
  })
  expect_false({
    validate_regex(
      bricks = list("start", "or", "1", "2", "end"),
      use_toast = FALSE
    )
  })
})
```


```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_regex_brick.Rmd",
  vignette_name = NA,
  check = FALSE,
  open_vignette = FALSE
)
```
