---
title: "Generate word"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

## Generate a word from a brick

```{r function-generate_from_brick}
#' Generate a word from a regex brick
#'
#' @param brick list. A list of the regex specifics
#' @param use_scrabble logical. Should the regex try to match a real word
#' @param maxword integer. Maximum number of random word to return
#' @param maxfreq integer. Boundary when no maximum occurrence is specified
#'
#' @importFrom purrr map_chr
#'
#' @return wordlist. A character string matching the regex.
#' @export
#'
#' @examples
generate_from_brick <- function(
    brick,
    use_scrabble = TRUE,
    maxword = 10,
    maxfreq = 10) {
  # verify brick list
  brick_items <- c(
    "brick",
    "type",
    "content",
    "occurrence",
    "custom_motif",
    "custom_occurrence"
  )

  if (!all(brick_items %in% names(brick))) {
    stop("brick input list does not have all required items")
  }

  # convert no max if custom range is used
  if (brick$occurrence == "custom") {
    up_bound <- sub(
      "no max",
      maxfreq,
      brick$custom_occurrence[2]
    )
    brick$custom_occurrence <- c(
      as.numeric(brick$custom_occurrence[1]),
      as.numeric(up_bound)
    )
  } else {
    brick$custom_occurrence <- c(0, 0)
  }

  if (brick$type == "ordered") {
    # repeat motif accoring to occurrence
    occurrence_equivalence <- list(
      "once" = 1,
      "at least once" = 1:maxfreq,
      "anytime" = 0:maxfreq,
      "custom" = brick$custom_occurrence[1]:brick$custom_occurrence[2]
    )
    motif_reps <- occurrence_equivalence[[brick$occurrence]]

    invented_match <- map_chr(motif_reps, \(x){
      paste(rep(brick$custom_motif, x), collapse = "")
    })

    use_duplicates <- length(invented_match) < maxword
    invented_match <- sample(
      invented_match,
      size = maxword,
      replace = use_duplicates
    )

    return(invented_match)
  } else if (brick$type == "unordered") {
    some_letters_in_regex <- any(
      c(
        "lowercase letters",
        "uppercase letters",
        "custom"
      ) %in% brick$content
    )
    if (use_scrabble && some_letters_in_regex) {
      scrabble_match <- search_in_scrabble_mem(brick)
    } else {
      scrabble_match <- c()
    }

    # generate from sampling
    extra_word_to_generate <- max(0, maxword - length(scrabble_match))
    if (extra_word_to_generate == 0) {
      return(sample(scrabble_match, maxword))
    } else {
      all_characters <- unlist(strsplit(rawToChar(as.raw(32:126)), ""))
      char_bucket <- list(
        "lowercase letters" = letters,
        "uppercase letters" = LETTERS,
        "digits" = 0:9,
        "punctuation" = grep("[[:punct:]]", all_characters, value = TRUE),
        "space and tab" = grep("[[:blank:]]", all_characters, value = TRUE),
        "wildcard" = grep(".", all_characters, value = TRUE),
        "custom" = strsplit(brick$custom_motif, "")
      )
      char_bucket <- unique(unlist(char_bucket[brick$content]))

      # complete scrabble list up to max_word
      if (brick$occurrence == "once") {
        repeats <- rep(1, extra_word_to_generate)
      } else if (brick$occurrence != "custom") {
        start_bound <- ifelse(
          brick$occurrence == "at least once",
          1,
          0
        )
        repeats <- sample(
          start_bound:maxfreq,
          size = extra_word_to_generate,
          replace = TRUE
        )
      } else if (brick$occurrence == "custom") {
        sample_range <- seq.int(
          from = as.numeric(brick$custom_occurrence[1]),
          to = min(c(maxfreq, as.numeric(brick$custom_occurrence[2])))
        )
        if (length(sample_range) == 1) {
          repeats <- rep(
            sample_range,
            extra_word_to_generate
          )
        } else {
          repeats <- sample(
            sample_range,
            size = extra_word_to_generate,
            replace = TRUE
          )
        }
      }
      invented_match <- map_chr(
        .x = repeats,
        .f = \(x) {
          paste0(
            sample(
              x = char_bucket,
              size = x,
              replace = TRUE
            ),
            collapse = ""
          )
        }
      )
      return(c(scrabble_match, invented_match))
    }
  }
}
```

```{r examples-generate_from_brick}
brick <- build_a_regex_brick(
  type = "ordered",
  occurrence = "custom",
  custom_motif = "heyho",
  content = NULL,
  custom_occurrence = c(5, 10)
)

generate_from_brick(brick)

brick <- build_a_regex_brick(
  type = "unordered",
  occurrence = "at least once",
  custom_motif = "write your motif here",
  content = c("digit")
)

generate_from_brick(brick)

brick <- build_a_regex_brick(
  type = "unordered",
  occurrence = "anytime",
  custom_motif = "WonDERFul",
  content = c("custom")
)

generate_from_brick(brick)
```

```{r tests-generate_from_brick}
test_that("function returns error for unexpected input", {
  expect_error(
    {
      generate_from_brick(brick = list())
    },
    regexp = "brick input list does not have all required items"
  )
})

test_that("function returns true match for ordered input", {
  brick <- list(
    brick = "(heyho){5,10}",
    type = "ordered",
    content = NULL,
    occurrence = "custom",
    custom_motif = "heyho",
    custom_occurrence = c(5, 10)
  )
  res <- generate_from_brick(brick)
  expect_true(all(grepl(pattern = brick$brick, x = res)))
})

test_that("function returns true match for unordered input", {
  brick <- list(
    brick = "[[:digit:]]+",
    type = "unordered",
    content = "digits",
    occurrence = "at least once",
    custom_motif = "write your motif here",
    custom_occurrence = NULL
  )

  res <- generate_from_brick(brick)
  expect_true(all(grepl(pattern = brick$brick, x = res)))
})

test_that("function returns true scarbble match for unordered input", {
  brick <- list(
    brick = "[WonDERFul]*",
    type = "unordered",
    content = "custom",
    occurrence = "custom",
    custom_motif = "WonDERFul",
    custom_occurrence = c(5, 10)
  )

  res <- generate_from_brick(brick)
  expect_true(all(grepl(pattern = brick$brick, x = res)))

  brick <- list(
    brick = "[zul]{4,4}",
    type = "unordered",
    content = "custom",
    occurrence = "custom",
    custom_motif = "zul",
    custom_occurrence = c(4, 4)
  )

  res <- generate_from_brick(brick)
  expect_true(all(grepl(pattern = brick$brick, x = res)))
})
```

## Search a word in Scrabble

```{r function-search_in_scrabble}
#' Search a word from Scrabble with regex
#'
#' @param brick list. A list of the regex specifics, works for unordered regex.
#'
#' @importFrom purrr map map_vec
#' @importFrom stringr str_extract_all
#'
#' @return wordlist. A character string matching the regex.
#'
#' @noRd
search_in_scrabble <- function(
    brick) {
  if (brick$type != "unordered") {
    stop("scrabble search is only available for unordered motifs")
  }
  wordlist <- lurex::wordlist

  # match full upper or full lower case
  match_all <- grep(
    pattern = paste0("^(", brick$brick, ")$"),
    x = c(wordlist, toupper(wordlist))
  )
  all_matches <- c(wordlist, toupper(wordlist))[match_all]

  universal_case <- all(
    c(
      "lowercase letters",
      "uppercase letters"
    ) %in% brick$content
  )

  if ("custom" %in% brick$content || universal_case) {
    # list which letter is found as upper or lower case
    if (universal_case) {
      letters_bucket <- map(.x = letters, .f = \(x){
        c(x, toupper(x))
      })
    } else {
      letters_bucket <- map_vec(.x = letters, .f = \(x){
        unique(
          str_extract_all(
            string = brick$custom_motif,
            pattern = paste0(c(x, toupper(x)), collapse = "|")
          )
        )
      })
    }
    names(letters_bucket) <- letters

    # scan wordlist match and pick correct case
    mixed_case_match <- map_chr(.x = all_matches, .f = \(word){
      paste(
        map(.x = strsplit(word, split = "")[[1]], \(word_letter){
          sample(letters_bucket[[tolower(word_letter)]], 1)
        }),
        collapse = ""
      )
    })

    all_matches <- c(all_matches, mixed_case_match)
  }

  return(unique(all_matches))
}

#' Search a word from Scrabble with regex with cache
#'
#' @inheritParams search_in_scrabble
#'
#' @importFrom memoise memoise
#'
#' @noRd
search_in_scrabble_mem <- memoise(search_in_scrabble)
```

```{r examples-search_in_scrabble}
search_in_scrabble(
  list(
    brick = "[zulu]{4,4}",
    type = "unordered"
  )
)

search_in_scrabble_mem(
  list(
    brick = "[zulu]{4,4}",
    type = "unordered"
  )
)
```

```{r tests-search_in_scrabble}
test_that("function returns error for unexpected input", {
  expect_error(
    search_in_scrabble(list("type" = "incorrect")),
    regexp = "scrabble search is only available for unordered motifs"
  )
})

test_that("function returns all matches for correct input", {
  res <- search_in_scrabble(
    list(
      brick = "[zulu]{4,4}",
      type = "unordered"
    )
  )

  expect_setequal(object = res, expected = c("lull", "lulu", "zulu"))
})
```

## Generate match from combined regex

```{r function-generate_from_regex}
#' List possible matches for a regex composed of multiple bricks
#'
#' @param brick_list list. A list of bricks.
#' @param n integer. The number of match to return.
#' @param n_bound integer. The number of character to add around match.
#' This will be aded if no start/end helper is detected.
#' @param use_scrabble logical. Should we first look for match in scrabble.
#'
#' @importFrom shiny tagList
#'
#' @return matchlist. A character string matching the regex.
#'
#' @noRd
generate_from_regex <- function(
    brick_list,
    brick_info,
    n = 10,
    n_bound = 5,
    use_scrabble = TRUE) {
  # verify presence of `or` groups
  if ("or" %in% brick_list) {
    # extract groups
    or_idx <- which(brick_list == "or")
    regex_groups <- findInterval(
      seq_along(brick_list),
      or_idx
    )
    # clean `or` from lists
    brick_list <- brick_list[-or_idx]
    regex_groups <- regex_groups[-or_idx]
  } else {
    regex_groups <- rep(1, length(brick_list))
  }

  # create by group
  groups_id <- unique(regex_groups)
  n_in_group <- ceiling(n / length(groups_id))

  list_of_n <- c()
  for (id in groups_id) {
    # verify presence of `start`/`end` helpers
    all_characters <- unlist(strsplit(rawToChar(as.raw(32:126)), ""))
    group_bricks <- brick_list[regex_groups == id]

    if (group_bricks[1] == "start") {
      char_before <- rep("", n_in_group)
      group_bricks <- group_bricks[-1]
    } else {
      char_before <- replicate(
        n_in_group,
        paste0(sample(all_characters, n_bound), collapse = "")
      )
    }

    if (group_bricks[length(group_bricks)] == "end") {
      group_bricks <- group_bricks[-length(group_bricks)]
      char_after <- rep("", n_in_group)
    } else {
      char_after <- replicate(
        n_in_group,
        paste0(sample(all_characters, n_bound), collapse = "")
      )
    }

    # generate each regex brick with maxword = n / (number of group)
    char_inside <- map(
      brick_info[group_bricks],
      \(x) {
        generate_from_brick(
          x,
          maxword = n_in_group,
          use_scrabble = use_scrabble
        )
      }
    )

    # col idx ?
    # how much brick before, except and/or/start
    col_idx <- min(which(regex_groups == id))
    if (col_idx > 1) {
      helper_before_idx <- sum(
        brick_list[1:col_idx - 1] %in% c("start", "end", "or")
      )
      col_idx <- col_idx - helper_before_idx
    }


    # bind them into final list of matches
    list_of_n_in_group <- color_style_regex(
      char_inside = char_inside,
      char_before = char_before,
      char_after = char_after,
      col_idx = col_idx
    )

    list_of_n <- c(list_of_n, list_of_n_in_group)
  }
  return(sample(list_of_n))
}

#' Style regex with colors
#'
#' @param char_inside character. A vector of regex match
#' if it contains helpers, helpers will be color in black
#' @param char_before character. A vector of random character before regex
#' @param char_after character. A vector of random character after regex
#' @param col_idx integer. A index to start the color vector from
#' @param is_regex logical. Take into account regex characters as black
#'
#' @importFrom purrr map_dbl map map_vec
#' @importFrom shiny tagList span
#'
#' @noRd
color_style_regex <- function(
    char_inside,
    char_before = NULL,
    char_after = NULL,
    col_idx = 1,
    is_regex = FALSE) {
  # check if regex is empty
  if (length(char_inside) == 0) {
    return(span(""))
  }

  # check size of vector
  if (is_regex) {
    vec_size <- 1
  } else {
    vec_size <- unique(map_dbl(char_inside, length))
  }

  # initialise palette
  color_pal_size <- length(char_inside)
  col_pal <- rep(lurex::color_pal, length.out = col_idx + color_pal_size)
  col_pal <- col_pal[col_idx:(col_idx + color_pal_size)]

  # style inner character (regex) with pkg color palette
  char_inside_with_style <- map(1:vec_size, .f = \(x) {
    # parse content (in multiple piece if match)
    if (!is_regex) {
      content <- map_vec(char_inside, x)
    } else {
      content <- char_inside
    }

    # apply color to each element, skip helper with black color
    nb_helper <- 0
    content_style <- list()
    for (idx in seq_along(content)) {
      if (is_regex && content[idx] %in% c("^", "|", "$")) {
        col_style <- "color:black"
        nb_helper <- nb_helper + 1
      } else {
        col_style <- paste0("color:", col_pal[idx - nb_helper])
      }
      content_style[[idx]] <- span(
        content[idx],
        style = col_style,
        .noWS = "outside"
      )
    }
    return(content_style)
  })

  # add grey boundary if provided
  if (!is_regex) {
    vec_boundary_size <- unique(length(char_before), length(char_after))

    if (length(vec_size) != 1 || vec_size != vec_boundary_size) {
      stop("The provided character vectors do not have the same length")
    }

    # bind them into final list of matches with grey extra boundaries
    list_of_n_in_group <- map(
      .x = 1:vec_size,
      .f = \(x) {
        p(
          span(char_before[x], style = "color:lightgrey", .noWS = "outside"),
          char_inside_with_style[[x]],
          span(char_after[x], style = "color:lightgrey", .noWS = "outside")
        )
      }
    )
    return(list_of_n_in_group)
  } else {
    return(tagList(char_inside_with_style[[1]]))
  }
}
```

```{r examples-generate_from_regex}
brick_list <- c("start", "1", "end")

brick_info <- list(
  `1` = build_a_regex_brick(
    type = "unordered",
    content = c("digits", "punctuation"),
    occurrence = "custom",
    custom_motif = "",
    custom_occurrence = c("6", "no max")
  )
)

generate_from_regex(
  brick_list = brick_list,
  brick_info = brick_info
)
```

```{r tests-generate_from_regex}
test_that("function returns regex with `or` helper", {
  brick_list <- c("start", "1", "end", "or", "start", "2", "end")

  brick_info <- list(
    `1` = list(
      brick = "[[:punct:]hello!]*",
      type = "unordered",
      content = c("punctuation", "custom"),
      occurrence = "anytime",
      custom_motif = "hello!",
      custom_occurrence = NULL
    ),
    `2` = list(
      brick = "(what's up \\?)",
      type = "ordered",
      content = NULL,
      occurrence = "once",
      custom_motif = "what's up ?",
      custom_occurrence = NULL
    )
  )

  n_to_test <- 12
  res <- generate_from_regex(
    brick_list = brick_list,
    brick_info = brick_info,
    n = n_to_test
  )

  expect_type(object = res, type = "list")
  expect_s3_class(object = res[[1]], class = "shiny.tag")
})

test_that("function returns regex without `or` helper", {
  brick_list <- c("start", "1", "2", "end")

  brick_info <- list(
    `1` = list(
      brick = "[[:punct:]hello!]*",
      type = "unordered",
      content = c("punctuation", "custom"),
      occurrence = "anytime",
      custom_motif = "hello!",
      custom_occurrence = NULL
    ),
    `2` = list(
      brick = "(what's up \\?)",
      type = "ordered",
      content = NULL,
      occurrence = "once",
      custom_motif = "what's up ?",
      custom_occurrence = NULL
    )
  )

  n_to_test <- 12
  res <- generate_from_regex(
    brick_list = brick_list,
    brick_info = brick_info,
    n = n_to_test
  )

  expect_type(object = res, type = "list")
  expect_s3_class(object = res[[1]], class = "shiny.tag")
})
```

```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_word_generator.Rmd",
  vignette_name = NA,
  check = FALSE,
  open_vignette = FALSE
)
```
