# WARNING - Generated by {fusen} from dev/flat_regex_brick.Rmd: do not edit by hand

test_that("function returns no warning for correct regex", {
  expect_true({
    validate_regex(bricks = list("yes", "or", "no"))
  })
})
