# WARNING - Generated by {fusen} from dev/flat_regex_brick.Rmd: do not edit by hand

test_that("function returns error for unexpected input", {
	expect_error({
		build_a_regex_brick(type = "unknown")
	})
	expect_error({
		build_a_regex_brick(content = "unknown")
	})
	expect_error({
		build_a_regex_brick(occurence = "unknown")
	})
	expect_error(
		{
			build_a_regex_brick(occurence = "custom")
		},
		regexp = "custom occurrence selected but no value given"
	)
	expect_error(
		{
			build_a_regex_brick(content = "custom")
		},
		regexp = "custom motif selected but no value given"
	)
})

test_that("function gives expected regex for ordered type", {
	regex_output <- build_a_regex_brick(
		type = "ordered",
		occurence = "custom",
		custom_motif = "hello",
		custom_occurrence = c(1, 5)
	)
	expect_equal(object = regex_output, expected = "(hello){1,5}")
})

test_that("function gives expected regex for unordered type", {
	regex_output <- build_a_regex_brick(
		type = "unordered",
		occurence = "anytime",
		custom_motif = "hello",
		content = c("lowercase letters", "uppercase letters", "custom")
	)
	expect_equal(object = regex_output, expected = "[[:lower:][:upper:]hello]*")
})
