# WARNING - Generated by {fusen} from dev/flat_regex_brick.Rmd: do not edit by hand

#' Build a regex brick
#'
#' @param type The type of regex group. Can be "ordered" or "unordered".
#' @param content The content of the regex group. Can be "wildcard", "lowercase letters", "uppercase letters", "digits", "punctuation", "space and tab", or "custom".
#' @param occurence The occurrence of the regex group. Can be "once", "at least once", "anytime", or "custom".
#' @param custom_motif The custom motif to be used in the regex group. Only applicable if "custom" is selected for the content parameter.
#' @param custom_occurrence The custom occurrence to be used in the regex group. Only applicable if "custom" is selected for the occurrence parameter.
#'
#' @return A character string representing the built regex.
#' @export
#'
#' @examples
#' build_a_regex_brick(
#'   type = "ordered",
#'   occurence = "custom",
#'   custom_motif = "hello",
#'   custom_occurrence = c(1, 5)
#' )
#'
#' build_a_regex_brick(
#'   type = "unordered",
#'   occurence = "anytime",
#'   custom_motif = "hello",
#'   content = c("lowercase letters", "uppercase letters", "custom")
#' )
build_a_regex_brick <- function(
    type = c("ordered", "unordered"),
    content = c("wildcard", "lowercase letters", "uppercase letters", "digits", "punctuation", "space and tab", "custom"),
    occurence = c("once", "at least once", "anytime", "custom"),
    custom_motif = NULL,
    custom_occurrence = NULL) {
  # check input
  type <- match.arg(type)
  content <- match.arg(content, several.ok = TRUE)
  occurence <- match.arg(occurence)

  # check cusom
  if ("custom" %in% occurence && is.null(custom_occurrence)) {
    stop("custom occurrence selected but no value given")
  }
  if ("custom" %in% content && is.null(custom_motif)) {
    stop("custom motif selected but no value given")
  }

  # set occurrence
  if (occurence != "custom") {
    occurrence_equivalence <- list(
      "once" = "",
      "at least once" = "+",
      "anytime" = "*"
    )
    custom_occurrence <- NULL
    freq <- occurrence_equivalence[occurence]
  } else {
    freq <- sprintf("{%i,%i}", custom_occurrence[1], custom_occurrence[2])
  }

  # set group
  if (type == "ordered") {
    group_bracket <- c("(", ")")

    # we only allow custom motif for ordered group for now
    text <- sprintf(
      "%s%s%s%s",
      group_bracket[1],
      custom_motif,
      group_bracket[2],
      freq
    )
    # remove unused parameters
    content <- NULL
  } else if (type == "unordered") {
    group_bracket <- c("[", "]")

    # set content
    regex_equivalance <- c(
      "wildcard" = ".",
      "lowercase letters" = "[:lower:]",
      "uppercase letters" = "[:upper:]",
      "digits" = "[:digit:]",
      "punctuation" = "[:punct:]",
      "space and tab" = "[:blank:]",
      "custom" = custom_motif
    )

    text <- sprintf(
      "%s%s%s%s",
      group_bracket[1],
      paste(regex_equivalance[content], collapse = ""),
      group_bracket[2],
      freq
    )
  }

  new_brick <- list(
    brick = text,
    type = type,
    content = content,
    occurence = occurence,
    custom_motif = custom_motif,
    custom_occurrence = custom_occurrence
  )

  return(new_brick)
}
