# WARNING - Generated by {fusen} from dev/flat_word_generator.Rmd: do not edit by hand

#' Search a word from Scrabble with regex
#'
#' @param brick list. A list of the regex specifics
#'
#' @importFrom purrr map2
#'
#' @return wordlist. A character string matching the regex.
#' @export
#'
#' @noRd
#' @examples
#' search_in_scrabble(brick = "morning")
search_in_scrabble <- function(
	brick) {
	# search work for unorderd (lower or upper case)
	match_all <- grep(
		pattern = paste0("^(", brick, ")$"),
		x = c(wordlist, toupper(wordlist))
	)

	# TODO : case-sensitive generation
	return(unique(wordlist[match_all]))
}
