# WARNING - Generated by {fusen} from dev/flat_regex_brick.Rmd: do not edit by hand

#' Validate a regex combination
#'
#' @param bricks character. The ordered list of regex bricks
#' @param use_toast logical. Should a UI toast be shown for incorrect regex.
#'
#' @return logical. Side effect : trigger a toast widget
#' @export
#'
#' @examples
#' validate_regex(
#' 	bricks = list("1", "end", "or", "2", "end", "or", "3", "4", "end")
#' )
validate_regex <- function(
	bricks,
	use_toast = TRUE
				) {
	# get idx
	or_idx <- which(bricks == "or")
	start_idx <- which(bricks == "start")
	end_idx <- which(bricks == "end")

	if (all(bricks %in% c("start", "end", "stop"))) {
		return(FALSE)
	}

	if ("start" %in% bricks) {
		# start can be found as 1st element or after a "or"
		if (!all(start_idx %in% c(1, or_idx + 1))) {
			make_a_toast(
				text = "start `^` should be the first element",
				use_toast = use_toast
			)
			return(FALSE)
		}
	}

	if ("end" %in% bricks) {
		if (!all(end_idx %in% c(length(bricks), or_idx - 1))) {
			make_a_toast(
				text = "end `$` should be the last element",
				use_toast = use_toast
			)
			return(FALSE)
		}
	}

	if ("or" %in% bricks) {
		is_first_or_last <- any(c(1, length(bricks)) %in% or_idx)

		if (is_first_or_last) {
			# cannot be first or last
			make_a_toast(
				text = "or `|` should not be 1st or last element",
				use_toast = use_toast
			)
			return(FALSE)
		}

		right_idx <- or_idx + 1[or_idx != length(bricks)]
		left_idx <- or_idx - 1[or_idx != 1]

		is_next_to_or <- any(
			c("or") %in% bricks[c(left_idx, right_idx)]
		)
		is_right_to_start <- any(
			"start" %in% bricks[left_idx]
		)
		is_left_to_end <- any(
			"end" %in% bricks[right_idx]
		)

		if (is_next_to_or) {
			make_a_toast(
				text = "or `|` should not be next to another `|`",
				use_toast = use_toast
			)
			return(FALSE)
		}

		if (is_right_to_start) {
			make_a_toast(
				text = "or `|` should not be directly after start `^`",
				use_toast = use_toast
			)
			return(FALSE)
		}

		if (is_left_to_end) {
			make_a_toast(
				text = "or `|` should not be directly before end `$`",
				use_toast = use_toast
			)
			return(FALSE)
		}
	}
	return(TRUE)
}

#' make a toast
#'
#' @param text character. The text to sho
#' @inheritParams validate_regex use_toast
#'
#' @importFrom shinyWidgets show_toast
#'
#' @noRd
make_a_toast <- function(text, use_toast) {
	if (isTRUE(use_toast)) {
		show_toast(
			title = "woups",
			text = text,
			type = "warning",
			timer = 3000,
			width = "400px",
			position = "top-end"
		)
	}
}
